/**
 * Generates src/components/Icon.jsx from the handful of Remix icons this app
 * actually uses.
 *
 * Importing remixicon's stylesheet costs 169 KB of CSS plus a 190 KB webfont to
 * draw about twenty glyphs, and drags 3 MB of legacy .svg/.ttf/.eot fonts into
 * the deploy. Inlining the paths costs a few KB and removes a network request
 * from the critical path — which matters, because this app is used on a phone.
 *
 * Add an icon by putting its name in ICONS and running `npm run icons`.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ICON_ROOT = join(root, 'node_modules', 'remixicon', 'icons');
const OUT = join(root, 'src', 'components', 'Icon.jsx');

const ICONS = [
  'add-line',
  'alert-line',
  'arrow-left-s-line',
  'arrow-right-s-line',
  'bar-chart-box-line',
  'calendar-line',
  'check-line',
  'checkbox-blank-circle-line',
  'checkbox-circle-fill',
  'clipboard-line',
  'close-line',
  'emotion-line',
  'flashlight-line',
  'group-line',
  'key-2-line',
  'list-check-2',
  'loader-4-line',
  'message-3-line',
  'phone-line',
  'save-line',
  'send-plane-fill',
  'settings-4-line',
  'sparkling-line',
  'subtract-line'
];

function findSvg(name, dir = ICON_ROOT) {
  for (const item of readdirSync(dir)) {
    const full = join(dir, item);
    if (statSync(full).isDirectory()) {
      const hit = findSvg(name, full);
      if (hit) return hit;
    } else if (item === `${name}.svg`) {
      return full;
    }
  }
  return null;
}

const entries = [];
const missing = [];
const multiPath = [];

for (const name of ICONS) {
  const file = findSvg(name);
  if (!file) {
    missing.push(name);
    continue;
  }
  const svg = readFileSync(file, 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) {
    missing.push(name);
    continue;
  }
  if (paths.length > 1) multiPath.push(name);
  entries.push([name, paths]);
}

if (missing.length) {
  console.error('Could not resolve icons:', missing.join(', '));
  process.exit(1);
}
if (multiPath.length) {
  console.log('Note: multi-path icons inlined as groups:', multiPath.join(', '));
}

const body = entries
  .map(([name, paths]) => `  '${name}': [${paths.map((d) => JSON.stringify(d)).join(', ')}]`)
  .join(',\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Run \`npm run icons\` after changing the ICONS list in that script.

const PATHS = {
${body}
};

/**
 * Sized in em so Tailwind's text-* utilities control it, exactly like the
 * webfont icons it replaces.
 */
export default function Icon({ name, className = '' }) {
  const paths = PATHS[name];
  if (!paths) return null;

  return (
    <svg
      className={className}
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      style={{ display: 'inline-block', verticalAlign: '-0.125em', flexShrink: 0 }}
    >
      {paths.map((d, i) => (
        <path key={i} d={d} />
      ))}
    </svg>
  );
}
`,
  'utf8'
);

const bytes = statSync(OUT).size;
console.log(`Wrote ${entries.length} icons to src/components/Icon.jsx (${(bytes / 1024).toFixed(1)} KB)`);
